//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StockDetails
    {
        public Guid Guid { get; set; }
        public string StockType { get; set; }
        public string ItemsID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> ItemwiseDiscount { get; set; }
        public Nullable<decimal> PricePerUnitAfterDiscount { get; set; }
        public Nullable<decimal> TotalPriceBeforeTax { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TotalPriceAfterTax { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string Name { get; set; }
        public string HSN_SAC_NO { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> MeasuringUnit { get; set; }
        public string Manufacture { get; set; }
        public string BarCode { get; set; }
        public string ItemUniqueDescription { get; set; }
        public string InvoiceNo { get; set; }
        public string PurchaseID { get; set; }
        public string SaleID { get; set; }
    }
}
